version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eth_wallet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/eth_wallet"

volumes:
  db-data:
