services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - .:/app

volumes:
  db-data:
